<section id="about" class="about_container">
    <div class="container_img_texture">
        <img class="about_up" src="assets/images/about-video.png" alt="masque de peinture blanche allant sur la vidéo">
    </div>
    <div class="about_flex container">
        <div class="about_article">
            <h2 class="h2 about_title">Qui suis-je ?</h2>
            <div class="about_text text">
                Après avoir descendu les sommets enneigés de Savoie, lézardé sur les plages Landaises lors d'emplois saisonniers, j'ai pris soin de personnes malades, âgées et handicapées. Ma curiosité m'a amenée dans une folle reconversion professionnelle : de la géographie à la cartographie, du SQL au développement web. C'est grâce à cette curiosité que vous vous retrouvez ici à lire ces quelques lignes sur mon premier site web.<br>Rêveuse et maman-chat à temps complet, je suis une passionnée de jeux en tout genre pourvu qu'il y ait du challenge.<br>
                Je vous invite à lire mon chemin de vie atypique, où l’apprentissage autodidacte, l’expérimentation et le travail m'ont conduite jusqu'à vous.
            </div>
        </div>
        <img class="about_img" src="assets/images/photo_sarah.png" alt="photo portrait Sarah Delaunay">
    </div>
</section>