<section id="about" class="about_container">
    <div class="container_img_texture">
        <img class="about_up" src="assets/images/about-video.png" alt="masque de peinture blanche allant sur la vidéo">
    </div>
    <div class="about_flex container">
        <div class="about_article">
            <h2 class="h2 about_title">Qui suis-je ?</h2>
            <div class="about_text text">
                <?php
                    $table='about';
                    $result= loadTable($table);
                    echo $result[0]['description']; 
                ?>
            </div>
        </div>
        <img class="about_img" src="assets/images/photo_sarah.png" alt="photo portrait Sarah Delaunay">
    </div>
</section>