<section id="expe" class="experiences_container">
    <div class="container_img_texture">
        <img class="expe_up" src="assets/images/expe-up.png" alt="peinture saumonée">
    </div>
    <h2 class="h2 experiences_title">Mes expériences</h2>
    <div class="timeline_item">
        <div class="timeline">
            <ul>
            <?php
                $table='experience';
                $experiences= loadTableDesc($table);
                foreach($experiences as $experience):?>
                    <li class="item_xp job">
                        <div class="item_xp_bloc" >
                            <div class="date_xp">
                                <?php if($experience['anneeFin'] == 0):?>
                                    <div><?=$experience['anneeDeb']?></div>
                                <?php else: ?>
                                    <div class="duo"><?=$experience['anneeFin']?> <br><?=$experience['anneeDeb']?></div>
                                <?php endif?>
                            </div>
                            <div class="content_xp">
                                <div class="titre_xp">
                                    <h3 class="h3_xp h3"><?=$experience['poste']?></h3>
                                </div>
                                <div class="resume_xp">
                                    <?php if(strlen($experience['entreprise']) > 19):?>
                                        <p class="entreprise"><i class="far fa-building"></i> <?=$experience['entreprise']?><br><i class="fas fa-map-marker-alt"></i> <?=$experience['ville']?></p>
                                    <?php elseif(strlen($experience['entreprise'])== 0): ?>
                                        <p class="entreprise"><?=$experience['description']?></p>  
                                    <?php else: ?>
                                        <p class="entreprise"><i class="far fa-building"></i> <?=$experience['entreprise']?><i class="fas fa-map-marker-alt"></i> <?=$experience['ville']?></p>     
                                    <?php endif?>
                                    <?php if(strlen($experience['entreprise'])> 0): ?>
                                        <p><?=$experience['description']?></p>      
                                    <?php endif?>   
                                </div>
                            </div> 
                        </div>
                    </li>
                <?php endforeach;?>
            </ul>
        </div>
    </div>
    <div class="container_img_texture">
        <img class="expe_down"src="assets/images/expe-down.png" alt="peinture rose">
    </div>
</section>