<div class="container_img_texture">
    <footer class="footer">
        <nav>
            <div>
                <a class="footer_marque" href="https://www.linkedin.com/in/sarah-delaunay/" target="_blank" >Sarah Delaunay<i class="fab fa-linkedin" ></i></a>     
            </div>
            <div footer_link>
                <a href="assets/images/cv_dev_junior_2019.pdf" download="CV_DELAUNAY_sarah">Télécharger mon CV</a>
                <a href="mentions_legales.php">Mentions légales</a>
            </div>
        </nav>
    </footer>
</div>