<head>
    <meta charset="utf-8"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <title>Sarah Delaunay | <?=$title?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no shrink-to-fit=no">

    <meta name="description" content="Portfolio de Sarah Delaunay Développeuse web">  
	<meta name="author" content=" Sarah Delaunay">
	<meta name = " keywords " content = " CV, portfolio, Curiculum Vitae , Delaunay" >
	<meta name = " generator " content = " BZH " >
	<meta name = " robots " content = " index,follow " >

    <link rel="icon" href="assets/images/favicon.ico">
    <!-- fichier css -->
        <link rel="stylesheet" type="text/css" media="screen" href="assets/styles/main.css">;
    

    <!-- Icon -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css" integrity="sha384-rtJEYb85SiYWgfpCr0jn174XgJTn4rptSOQsMroFBPQSGLdOC5IbubP6lJ35qoM9" crossorigin="anonymous">
    <!-- Font -->
    <link href="https://fonts.googleapis.com/css?family=Lato|Zeyada&display=swap" rel="stylesheet"> 

    <!-- JavaScript -->
    <!-- Script -->
    <script type="text/javascript" src="assets/scripts/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="assets/scripts/main.js"></script> 
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>

</head>
