<header class="header_container">
    <nav role="navigation" class="nav_container">
        <div class="logo_container">
            <a href="#intro" class="burger_title">Sarah Delaunay </a>
        </div> 
        <div>
            <input id="menu-toggle" type="checkbox" />
            <label class="menu-button-container" for="menu-toggle">
                <div class="menu-button"></div>
            </label>
            <ul class="menu">
                <li><a class="nav_link" href="index.php?#intro">Accueil</a></li>
                <li><a class="nav_link" href="index.php?#about">A propos de moi</a></li>
                <li><a class="nav_link" href="index.php?#expe">Expériences</a></li>
                <li><a class="nav_link" href="index.php?#skills">Compétences</a></li>
                <li><a class="nav_link" href="index.php?#projects">Projets</a></li>
                <li><a class="nav_link" href="index.php?#cv">CV</a></li>
                <li><a class="nav_link" href="index.php?#contact">Contact</a></li>
            </ul>
        </div>
    </nav>
</header>
