<section id="projects"class="projects_container">
    <div class="container_img_texture">
        <img class="projet_up" src="assets/images/projet-up.png" alt="peinture rose">
    </div>
    <h2 class="h2 projets_title">Mes réalisations</h2>
    <div class="project_list">
    <?php
        $table='projects';
        $projets= loadTable($table);
        foreach($projets as $projet):?>
        <div class="project">
            <div class="face-side">
                <a class="project_url" href="#projects">
                    <img class="project_img" src="assets/images/uploads/projets/<?=$projet['image']?>" alt="<?=$projet['titre']?>">
                </a>
            </div>
            <div class="hover-side">
            <?php if(strlen($projet['url'])> 0): ?>
                <a class="project_url" href="<?=$projet['url']?> " target="_blank">
            <?php else :?> 
                <a class="project_url" href="#projects">
            <?php endif?>    
                    <p class="h3"><?=$projet['description']?></p>
                    <p><?=$projet['language']?></p>
                </a>
            </div>
        </div>
        <?php endforeach;?>
    </div>
    <div class="container_img_texture">
        <img class="projet_down"src="assets/images/projet-down.png" alt="peinture rose">
    </div>
</section>