<section id="skills" class="skills_container">
    <h2 class="h2 skills_title">Mes cartes à jouer</h2>
    <div class="container">
        <img class="tache_rose" src="assets/images/tache_rose.png" alt="tache rose">
    <h3 class="h3 skills_sub_title">Compétences techniques </h3>
    <?php include('views/components/card_deck.phtml');?>
    <div class="container_img_texture">
        <img class="tache_jaune"src="assets/images/tache-jaune.png" alt="tache jaune">
    </div>
    <h3 class="h3 skills_sub_title">Qualités humaines et professionnelles</h3>
    <?php include('views/components/banner_icon.phtml');?>
    </div>
</section>