<!-- icones se trouvant dans la session compétences -->
<div class="banner_container container">
    <div class="item_container">
        <img class="icon" src="assets/images/icones/travail_equipe.svg" alt="Travail en equipe">
        <h4 class="h4 icon_title">Travail en équipe</h4>
    </div>
    <div class="item_container">
        <img class="icon" src="assets/images/icones/curiosity.svg" alt="Curiosite">
        <h4 class="h4 icon_title">Curiosité</h4>
    </div>
    <div class="item_container">
        <img class="icon" src="assets/images/icones/perseverance.svg" alt="Perseverance">
        <h4 class="h4 icon_title">Perseverance</h4>
    </div>
    <div class="item_container">
        <img class="icon" src="assets/images/icones/bienveillance.svg" alt="Bienveillance">
        <h4 class="h4 icon_title">Bienveillance</h4>
    </div>
    <div class="item_container">
        <img class="icon" src="assets/images/icones/organisation.svg" alt="organisation">
        <h4 class="h4 icon_title">Organisation</h4>
    </div>
</div>