<!-- icones se trouvant dans la session compétences -->
<div class="banner_container container">
<?php
    $table='qualite';
    $qualites= loadTableDesc($table);
    foreach($qualites as $qualite):?>
    <div class="item_container">
        <img class="icon" src="assets/images/uploads/qualites/<?=$qualite['icone']?>" alt="<?=$qualite['titre']?>">
        <h4 class="h4 icon_title"><?=$qualite['titre']?></h4>
    </div>
    <?php endforeach;?>
</div>