<!-- Liste des cartes de la session compétences -->
<ul class="cards">
    <li class="card-container">
        <div class="card">
            <div class="side">
                <div class="img_border">
                    <img src="assets/images/icones/html5_icon.svg" alt="html">
                </div>            
            </div>
            <div class="side back">
                <img src="assets/images/icones/html5_icon.svg" alt="html">
                <div class="level">Débutant</div>
                <div class="other">
                    J'ai appris le html lors de ma licence en géomatique et ma formation à la 3WA. Puis j'ai approfondi mon apprentissage sur deux projets sur lesquels j'ai travaillé chez <strong>Yeswedev</strong>.
                </div>
            </div>
        </div>
    </li>
    <li class="card-container">
        <div class="card">
            <div class="side">
                <div class="img_border">
                    <img src="assets/images/icones/css3_icon.svg" alt="css">
                </div>            
            </div>
            <div class="side back">
                <img src="assets/images/icones/css3_icon.svg" alt="css">
                <div class="level">Débutant</div>
                <div class="other">
                    J'ai appris le css lors de ma licence en géomatique et ma formation à la 3WA. Puis j'ai approfondi mon apprentissage sur deux projets sur lesquels j'ai travaillé chez <strong>Yeswedev</strong>.
                </div>
            </div>
        </div>
    </li>
    <li class="card-container">
        <div class="card">
            <div class="side">
                <div class="img_border">
                    <img src="assets/images/icones/js_icon.svg" alt="javascript">
                </div>            
            </div>
            <div class="side back">
                <img src="assets/images/icones/js_icon.svg" alt="javascript">
                <div class="level">Débutant</div>
                <div class="other">
                    J'ai appris javascript lors de ma formation à la 3WA. Puis j'ai approfondi mon apprentissage sur deux projets sur lesquels j'ai travaillé chez <strong>Yeswedev</strong>.
                </div>
            </div>
        </div>
    </li>
    <li class="card-container">
        <div class="card">
            <div class="side">
                <div class="img_border">
                    <img src="assets/images/icones/php_icon.svg" alt="php">
                </div>            
            </div>
            <div class="side back">
                <img src="assets/images/icones/php_icon.svg" alt="php">
                <div class="level">Débutant</div>
                <div class="other">
                    J'ai appris le php lors de ma formation à la 3WA. Puis j'ai approfondi mon apprentissage sur deux projets sur lesquels j'ai travaillé chez <strong>Yeswedev</strong>.
                </div>
            </div>
        </div>
    </li>
    <li class="card-container">
        <div class="card">
            <div class="side">
                <div class="img_border">
                    <img src="assets/images/icones/git_icon.svg" alt="git">
                </div>            
            </div>
            <div class="side back">
                <img src="assets/images/icones/git_icon.svg" alt="git">
                <div class="level">Débutant</div>
                <div class="other">
                    J'utilise git depuis que j'ai travailé chez <strong>Yeswedev</strong>. C'est un formidable outil de travail en équipe et de partage.
                </div>
            </div>
            
            
        </div>
    </li>
    <li class="card-container">
        <div class="card">
            <div class="side">
                <div class="img_border">
                    <img src="assets/images/icones/mysql_icon.svg" alt="mysql">
                </div>            
            </div>
            <div class="side back">
                <img src="assets/images/icones/mysql_icon.svg" alt="mysql">
                <div class="level">Intermédiaire</div>
                <div class="other">
                    J'ai découvert mySQL lors de ma licence de géomatique. Puis j'ai travaillé avec sur les deux projets sur lesquels j'ai travaillé chez <strong>Yeswedev</strong>.
                </div
            </div>
        </div>
    </li>
    <li class="card-container">
        <div class="card">
            <div class="side">
                <div class="img_border">
                    <img src="assets/images/icones/postgresql_icon.svg" alt="postgresql">
                </div>            
            </div>
            <div class="side back">
                <img src="assets/images/icones/postgresql_icon.svg" alt="postgresql">
                <div class="level">Intermédiaire</div>
                <div class="other">
                    J'ai découvert postgreSQL lors de ma licence pro de géomatique et je l'ai utilisé <span class="important_word">quotidiennement</span> lors de mon stage à la <strong>DDTM</strong>.
                </div>
            </div>
        </div>
    </li>
    <li class="card-container">
        <div class="card">
            <div class="side">
                <div class="img_border">
                    <img src="assets/images/icones/npm_icon.svg" alt="npm">
                </div>            
            </div>
            <div class="side back">
                <img src="assets/images/icones/npm_icon.svg" alt="npm">
                <div class="level">Débutant</div>
                <div class="other">
                    J'ai découvert NPM chez <strong>Yeswedev</strong>, je l'ai utilisé sur tous les projets sur lesquels j'ai travaillé .
                </div>
            </div>
        </div>
    </li>
    <li class="card-container">
        <div class="card">
            <div class="side">
                <div class="img_border">
                    <img src="assets/images/icones/sass_icon.svg" alt="sass">
                </div>            
            </div>
            <div class="side back">
                <img src="assets/images/icones/sass_icon.svg" alt="sass">
                <div class="level">Intermédiaire</div>
                <div class="other">
                    J'ai découvert Sass lors de ma formation à la <strong>3WA</strong> et je l'ai utilisé sur tous les projets sur lesquels j'ai travaillé chez <strong>Yeswedev</strong>.
                </div>
            </div>
        </div>
    </li>
    <li class="card-container">
        <div class="card">
            <div class="side">
                <div class="img_border">
                    <img src="assets/images/icones/wordpress_icon.svg" alt="wordpress">
                </div>            
            </div>
            <div class="side back">
                <img src="assets/images/icones/wordpress_icon.svg" alt="wordpress">
                <div class="level">Débutant</div>
                <div class="other">
                    J'ai découvert wordpress lors de ma formation à la 3WA. Puis j'ai approfondi mon apprentissage sur deux projets sur lesquels j'ai travaillé chez <strong>Yeswedev</strong>.
                </div>
            </div>
        </div>
    </li>
    <li class="card-container">
        <div class="card">
            <div class="side">
                <div class="img_border">
                    <img src="assets/images/icones/ai_icon.svg" alt="adobe illustrator">
                </div>            
            </div>
            <div class="side back">
                <img src="assets/images/icones/ai_icon.svg" alt="adobe illustrator">
                <div class="level">Intermédiaire</div>
                <div class="other">
                    J'ai appris à utiliser cette outils lors de ma licence de géographie, j'ai également proposé une formation de cet outil lors de mon stage à la <strong>DDTM</strong>. J'ai créé le logo de ce site grâce à cet outil.
                </div>
            </div>
        </div>
    </li>
    
</ul>