<!-- Liste des cartes de la session compétences -->
<ul class="cards">
<?php
    $table='skill';
    $competences= loadTableDesc($table);
    foreach($competences as $competence):?>
    <li class="card-container">
        <div class="card">
            <div class="side">
                <div class="img_border">
                    <img src="assets/images/uploads/competences/<?=$competence['icone']?>" alt="<?=$competence['titre']?>">
                </div>            
            </div>
            <div class="side back">
                <img src="assets/images/uploads/competences/<?=$competence['icone']?>" alt="<?=$competence['titre']?>">
                <div class="level"><?=$competence['niveau']?></div>
                <div class="other">
                <?=$competence['description']?>
                </div>
            </div>
        </div>
    </li>
    <?php endforeach;?>
</ul>