<!-- Introduction  -->
<section id="intro" class="hero container_shadow" >
    <video src="assets/videos/Korea - 26356.mp4" type="video/mp4" autoplay loop ></video>
    <div class="container_pulse">
        <svg class="pulse" viewBox="0 0 1024 1024">
            <circle class="circle" cx="512" cy="512" r="512"></circle>
            <circle class="circle" cx="512" cy="512" r="512"></circle>
            <circle class="circle" cx="512" cy="512" r="512"></circle>
        </svg>
        <div class="container_circle  ">
            <img src="assets/images/logo_hero.svg
            " alt="Logo Sarah Delaunay" class="img_hero">
            <h1 class="h1 title_hero">Sarah Delaunay</h1>
            <h2 class="title_hero--sub"> Développeuse-intégratrice </br> web</h2>
        </div>
    </div>
    
</section>