<!DOCTYPE html>
<html lang="fr">

    <?php include('views/partials/head.phtml');?>

    <body>

        <!-- Navigation -->
        <?php include('views/partials/header.phtml');?>
        <main>
            <!-- Page Content -->
            <section class="content">
                <?php include('views/components/hero.phtml');?>
                <?php include('views/partials/about.phtml');?>
                <?php include('views/partials/experiences.phtml');?>
                <?php include('views/partials/skills.phtml');?>
                <?php include('views/partials/projects.phtml');?>
                <?php include('views/partials/cv.phtml');?>
                <?php include('views/partials/contact.phtml');?>
            </section>
        </main>
        <!-- Footer -->

        <?php include('views/partials/footer.phtml');?>
        
    </body>


</html>
