<head>
    <meta charset="utf-8"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <title>Back office | <?=$title?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no shrink-to-fit=no">

    <meta name="description" content="Administration du Portfolio de Sarah Delaunay Développeuse web">  
	<meta name="author" content=" Sarah Delaunay">
	<meta name = " robots " content = " noindex,nofollow " >

    <link rel="icon" href="../assets/images/favicon.ico">
    <!-- fichier css -->
        <link rel="stylesheet" type="text/css" media="screen" href="../assets/styles/main.css">
    

    <!-- Icon -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css" integrity="sha384-rtJEYb85SiYWgfpCr0jn174XgJTn4rptSOQsMroFBPQSGLdOC5IbubP6lJ35qoM9" crossorigin="anonymous">
    <!-- Font -->
    <link href="https://fonts.googleapis.com/css?family=Lato|Zeyada&display=swap" rel="stylesheet"> 

    <!-- JavaScript -->
    <!-- Script -->
    <script type="text/javascript" src="../assets/scripts/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="../assets/scripts/main.js"></script>
    <script src="https://cdn.tiny.cloud/1/w4vatwznl5fjkvo6pc5znh1w4nmedyvdun17txxwqv6adae4/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
    tinymce.init({
        selector: '#tinyMce',

    });
    </script>
  

</head>
