<section class="bo_form">
<h1 class="h1 bo_title1">Ajouter votre nouveau cv</h1>
    <form action="addCv.php" method="POST" enctype="multipart/form-data" >
        <input class="bo_form_item" type="file" id="cvForm" name="cvForm" accept=".png, .jpg, .pdf, .jpeg ">
        <button class="bo_form_button" type="submit" class="bo_form_button"> valider </button>
        <p><strong>Note:</strong> Seuls les formats .pdf, .jpg, .jpeg .png sont autorisés </p>
    </form>
</section>