<section class="bo_form login" >
    <form  action="login.php" method="POST" class="container">
        <fieldset>
            <legend>Connectez-vous</legend>
        
            <div class="bo_form_item">
                <label for="inputEmail">Adresse e-mail</label>
                <input type="email"  id="inputEmail" aria-describedby="emailHelp" placeholder="Entrez votre email" name="email">
            </div>
            <div class="bo_form_item">
                <label for="inputPassword">Mot de passe</label>
                <input type="password"  id="inputPassword" placeholder="Mot de passe" name="password">
            </div>
            
        </fieldset>
            <button type="submit" class="bo_form_button">Se connecter</button>
        </fieldset>
    </form>
</section>